version: "3.6"

name: context
services:
  web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - "4000:80"
    networks:
      apps:
    links:
      - db
      - server
    depends_on:
      - db
      - server

  server:
    build:
      context: server
    image: "${IMAGE_NAME_BACKEND}:${GITHUB_SHA}"
    environment:
      - PORT=80
      - DATABASE=http://admin:password@db:5984
    restart: always
    links:
      - db
    depends_on:
      - db
    networks:
      apps:

  db:
    container_name: insomnia_couchdb
    image: couchdb
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    restart: always
    networks:
      apps:
    volumes:
      - couchdb_data:/opt/couchdb/data
      - ./couchdb.ini:/opt/couchdb/etc/local.ini

volumes:
  couchdb_data:

networks:
  apps:
    external: true
