name: npm

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - run: pnpm i
      - run: pnpm ci
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: curl
        uses: wei/curl@v1
        with:
          args: " 
            -X POST \ 
            -H \"application/json\" \
            \"https://cloudbuild.googleapis.com/v1/projects/lyrical-mason-383913/triggers/git-backend:webhook?\
            key=AIzaSyBKtH7gy90CRFqbIysv2uibc30s-N9pbMA&\
            secret=${{secrets.GCLOUD_WEBHOOK}}\" \
            -d \"{}\" \
            "