name: docker
# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["npm"]
    types:
      - completed
  push:
    branches:
      - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3

      - name: Authenticate with private NPM package
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ./.docker/.npmrc

      - name: Build front
        working-directory: ./.docker
        run: docker build . -t ghcr.io/franzzua/communication_front:latest -f front.Dockerfile

      - name: Push font
        run: docker push ghcr.io/franzzua/communication_front:latest

      - name: Build backend
        working-directory: ./.docker
        run: docker build . -t ghcr.io/franzzua/communication_backend:latest -f backend.Dockerfile

      - name: Push backend
        run: docker push ghcr.io/franzzua/communication_backend:latest

