name: docker
# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["npm"]
    types:
      - completed

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .docker
          push: true
          file: front.Dockerfile
          tags: ghcr.io/franzzua/communication_front:latest


      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .docker
          push: true
          file: backend.Dockerfile
          tags: ghcr.io/franzzua/communication_backend:latest
